### ISSUE TITLE
CI randomly fails 

### ISSUE THREAD

**Issue by yuanfeiz** [ethereum/ens#112]
I can't figure out what's going on, just asked a question at http://ethereum.stackexchange.com/questions/13943/testrpc-undeterministically-throw-invalid-opcode

**Comment by Arachnid** [comment]
I'm fairly sure it's a timing issue: we rely on advancing time in various tests, and if the tests happen to start at the wrong (real) time, the extra second we add at the end may not be enough. This would likely be fixed by changing the places where we add one second, and instead add a larger time interval  (a minute, say).
