### ISSUE TITLE
Deed has no tests?

### ISSUE THREAD

**Issue by ethers** [ethereum/ens#122]
https://github.com/ethereum/ens/blob/5c2167b9fc6290c180e3989a30b4f9f4e3213d5a/contracts/HashRegistrarSimplified.sol#L24 does not appear to have direct tests.

Why is setBalance payable?
https://github.com/ethereum/ens/blob/5c2167b9fc6290c180e3989a30b4f9f4e3213d5a/contracts/HashRegistrarSimplified.sol#L65
Instead of `payable`, `external` would make it clear that the function is called by another contract.

Does destroyDeed need to be `public`, which it implicitly is, or would it be better to be `internal`?

**Comment by Arachnid** [comment]
> https://github.com/ethereum/ens/blob/5c2167b9fc6290c180e3989a30b4f9f4e3213d5a/contracts/HashRegistrarSimplified.sol#L24 does not appear to have direct tests.

It's tested via the registrar tests, since it's a component of the registrar.

> Why is setBalance payable?
https://github.com/ethereum/ens/blob/5c2167b9fc6290c180e3989a30b4f9f4e3213d5a/contracts/HashRegistrarSimplified.sol#L65

Legacy reasons. Removing this modifier was one of the issues identified by the audits.

> Does destroyDeed need to be public, which it implicitly is, or would it be better to be internal?

It needs to be public, so that if it failed the first time, the owner of the deed can fix the problem and call it again themselves.
