### ISSUE TITLE
Where does the difference between Actual Bid Amount and Bid Mask go?

### ISSUE THREAD

**Issue by rwyoko** [ethereum/ens#217]
Hi,
I did bid for a .eth name through MyEtherWallet and used for the bid mask a higher value than for the actual bid amount. This difference never returned to my account, I just see it as an internal transaction (the 1.45ETH):
https://etherscan.io/address/0xa1308820eacf53d56133c5980fEb4A862Cf678c1#internaltx
Thanks in advance,
Robert

**Comment by veox** [comment]
You mean [this transaction](https://etherscan.io/tx/0xce66ad2e374596597360e1ac2f52a5013b4aad77bb76eaac3f6121824a9cd1a1)?

Well, the page says that it _has_ been returned to your account.

"Internal" transactions is just EtherScan's way of tracking messages that were made by accounts with associated code (contracts), as compared to those without it, which are often called "externally owned", or "external".

The confusion that arises from this nomenclature is due to the thinking process of:

> Well, there's "externally owned" accounts, let's call them "external" for short.
>
> They send messages initiated by humans, which are logged in the chain directly, as "transactions" in blocks - let's call them "external", too.
>
> Those messages sometimes go to other accounts, which are very different, let's call them something opposite... "internal"!
>
> Contracts can send messages, too, which are not logged as "transactions", but whose effects are still recorded as part of "state change", or "state"... Let's call these... "Internal transactions"!

And - here we are. The "internal transaction" _is_ in fact how the ETH got back to your external account, from the respective bid's `Deed` contract.
