### ISSUE TITLE
Entered into unexpected auction

### ISSUE THREAD

**Issue by jhabdas** [ethereum/ens#252]
**ALL BIDDING SHOULD BE SUSPENDED UNTIL THIS IS ADDRESSED AND RESOLVED.**

To test ENS out and using Brave `0.19.95` with MetaMask `3.12.0` I placed a bid from `registrar.ens.domains` for `desiredaddress.eth` and received a MetaMask request for the same amount at the same time of my bid and was entered into a [completely different auction](https://etherscan.io/tx/0xe4e31ab857666abab60dbccccd117ab6c2d7b9a56849bd98adea2b002d099099).

The terms of ENS state:

> After that time, a 48 hour reveal phase starts during which, anyone who bids must reveal their bids (failing to do so will result in irreversible loss of funds).

The above statement simply cannot be so when one is sent into an incorrect ENS—resulting in guaranteed total loss as a result of having no backup of SALT or other info needed to reveal bid.

**Comment by Arachnid** [comment]
Your bid is on the correct name; the registrar also opens two random 'chaff' auctions. Is `desiredaddress.eth` the literal name you bid on?

There is a bug where it will occasionally not open the auction you are bidding on; in that case you will need to manually open that auction (you do not have to place another bid) in order to be able to reveal your bid at the appropriate time. You can do this by reloading the interface and clicking 'open without bidding'.

Future bugs should be filed against ethereum/ens-registrar-dapp.

**Comment by jhabdas** [comment]
I'll take that into consideration though I found it highly confusing and somewhat deceptive to show anything at all when starting my auction and placing my bid. And because of the auto-burn I think you're doing this wrong.
